name: AnyMeal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt install -y flex googletest librecode-dev libsqlite3-dev qtbase5-dev-tools qttools5-dev-tools qtbase5-dev pkgconf
    - name: create configure script
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: check
      run: make check
    - name: distributable
      run: make dist-xz
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: anymeal-source
        path: anymeal-*.tar.xz
  windows-installer:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        install: >-
          git gcc mingw-w64-x86_64-make autoconf automake flex bison mingw-w64-x86_64-sqlite3 mingw-w64-x86_64-gtest
          mingw-w64-x86_64-recode mingw-w64-x86_64-qt5-base mingw-w64-x86_64-qt5-tools mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-nsis
    - run: ./autogen.sh
    - name: create configure script
      run: ./autogen.sh
    - name: configure
      run: ./configure.mingw
    - name: make
      run: make
    - name: check
      run: make check
